### PR TITLE
Fixed error sending more than 256 fragments <1.9.x> [7403]

### PR DESCRIPTION
**Pull request by richiware**
The async thread was not awaken to send the next unsent fragments after sending the first 256. This PR fixes this.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1254/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1041/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1251/)

**Comment by dirk-thomas** [comment]
I can confirm that this patch makes it work for the use case where the number of UDP packets a data sample is split to is getting high. Thank you for the quick fix!

**Comment by dirk-thomas** [comment]
@richiware Please see the related feature request: #976.

**Comment by dirk-thomas** [comment]
Can you please clarify if this bug has always existed or if not in which version it was introduced?

**Comment by MiguelCompany** [comment]
> Can you please clarify if this bug has always existed or if not in which version it was introduced?

I think it was introduced on #486, where we changed FragmentNumberSet_t from a std::set to a fixed sized bitmap. So it has probably been there since release 1.8.0.

@richiware Could you address the proposed changes, and then backport the fix to 1.8.x?

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1270/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1056/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1267/)

**Comment by MiguelCompany** [comment]
Failed tests are not related

**Pull request merged**
