### PR TITLE
[ros2-eloquent] Simulate initial acknack on ReaderProxy::start() [7974]

### PR DESCRIPTION
**Pull request by adolfomarver**
This is a backport of #1045

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@mjcarroll @dirk-thomas Would someone please run a ROS2 CI build for this eloquent backport?

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9723/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5367/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7916/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9608/)

**Comment by mjcarroll** [comment]
Rebuilding network errors:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9740/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9613/)

**Comment by MiguelCompany** [comment]
@mjcarroll Are the failures unrelated to this PR?

**Comment by mjcarroll** [comment]
As far as Linux, yes, it looks like we keep losing our AWS instances for some reason.

There are also some issues with the test reporting causing jobs to go unnecessarily red.  Those should be solved by: https://github.com/ament/ament_cmake/pull/229 and  https://github.com/ament/ament_lint/pull/222

Going through the results manually, I don't see anything that would cause me to believe it's related to this PR.

**Comment by MiguelCompany** [comment]
> Going through the results manually, I don't see anything that would cause me to believe it's related to this PR.

Great! Merged then!

**Pull request merged**
