### PR TITLE
add requested boost components to the error message

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Another approach would be to pass `REQUIRED` in the line above:

    find_package(Boost REQUIRED COMPONENTS ${ARGN})

Then you can remove all the custom checking and error messaging since CMake will fail directly if the dependencies can't be found.

**Comment by richiprosima** [comment]
Last commit from our internal Git contains your last suggestion. Thanks.

**Comment by dirk-thomas** [comment]
Will the change be available in this repository at some point?

**Comment by dirk-thomas** [comment]
Seems to be in this repo by now: https://github.com/eProsima/Fast-RTPS/blob/eb6ecddf018ddd0552c25a3ed298546e2c4fe92f/cmake/dev/boost_libraries.cmake#L21

**Pull request closed without merging**
