### PR TITLE
Fixed the lock ordering between EDP and PDP

### PR DESCRIPTION
**Pull request by guillaumeautran**
Fixed a deadlock problem when removing writer proxies / reader proxies releasing the PDP mutex pior to going down proxies. 

Also, converted some pointers to smart pointers to avoid memory leakage.

Issue: #190

### CODE REVIEW

**Comment by dhood** [comment]
This PR resolves the deadlocking described in https://github.com/eProsima/Fast-RTPS/issues/200

**Comment by dhood** [comment]
Could you let us know if this is likely to be reviewed in the next week, please? (We understand that your team is busy, we just need to do something about the ROS 2 tests that are failing from https://github.com/eProsima/Fast-RTPS/issues/200, and an ETA on this PR will help us decide if we should pin fastrtps or just wait). Thanks!

**Comment by JaimeMartin** [comment]
Hi dhood,

yes, we will review this PR next week.

**Comment by richiware** [comment]
@guillaumeautran Last week a fellow worker tells me he detected a segmentation fault using your PR. I've checked it right now and get it too. 

```
1: [ RUN      ] BlackBox_PreallocMem.EndpointRediscovery
1: Writer is waiting discovery...
1: Writer discovery finished...
1: Reader is waiting discovery...
1: Reader discovery finished...
1: Writer is waiting removal...
1: Writer removal finished...
1: Writer is waiting discovery...
1/1 Test #1: BlackboxTests_PreallocMem ........***Exception: SegFault 28.27 sec
```

It's good your intention of use shared_ptr, but I believe it has repercutions  knowing how that part is designed.
Anyway you can run our tests using `ctest`. Previously our `CMakelists.txt` has to have detected googletest libraries.

**Comment by guillaumeautran** [comment]
Thanks for the feedback! Let me have a look.

**Comment by guillaumeautran** [comment]
Yeap, I see it now. The problem is the suicidal timer [TimedEventImpl.cpp](https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/resources/TimedEventImpl.cpp#L221) deleting itself. With shared pointers, once the last reference is cleared, the memory is deleted without delay. 

Now, does that not worry you to have a class basically doing a delete on the this pointer?

**Pull request closed without merging**
