### PR TITLE
Refs #5433 Update CDR & IDL [5446] [5472]

### PR DESCRIPTION
**Pull request by LuisGP**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1752/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1711/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1723/)

**Comment by TSC21** [comment]
This was tested on my side with success. Will this be brought as an hotfix to 1.8.0?

**Comment by TSC21** [comment]
@LuisGP @richiware when do you plan to bring this in?

**Comment by TSC21** [comment]
@MiguelCompany any plans? I recall this is a blocking bug...

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1768/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1727/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1739/)

**Comment by TSC21** [comment]
@richiware updates?

**Comment by richiware** [comment]
Test failed not related.

**Comment by TSC21** [comment]
@richiprosima is it a 1.8.1 release planned soon so to bring this in? Thanks!

**Comment by richiware** [comment]
We are working on it. It will be released in three weeks.

**Pull request merged**
