### PR TITLE
[master] Correct clang warnings due to overwritten methods [7236]

### PR DESCRIPTION
**Pull request by EduPonz**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1140/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/955/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1140/)

**Comment by EduPonz** [comment]
Results were the changes are actually applied can be seen in [CI build 1202](http://ci.intranet.eprosima.com:8080/job/FastRTPS%20Manual/1202/). The failure in windows is expected cause #953 is not applied in the branch

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1171/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/971/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1168/)

**Comment by EduPonz** [comment]
Failure on Windows [toolset v141](http://ci.intranet.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1168/label=windows-secure,toolset=v141/console) due to jenkins expection. The tests have passed.

**Pull request merged**
