### PR TITLE
link atomic under clang

### LINKED ISSUE #1223: linker error under clang with atomic funcitons
## Expected Behavior
When building under Clang, the build should succeed.

## Current Behavior
Packages downstream fail due to a linker error with `libfastrtps.so.2.0.0`.
```
--- stderr: rmw_fastrtps_shared_cpp                                                                                         
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_compare_exchange
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_load
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_store
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/CMakeFiles/test_security_logging.dir/build.make:112: test/test_security_logging] Error 1
make[1]: *** [CMakeFiles/Makefile2:203: test/CMakeFiles/test_security_logging.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rmw_fastrtps_shared_cpp	[ Exited with code 2 ]
```

```
--- stderr: test_msgs                                                                                                          
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_compare_exchange
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_load
ld.lld: error: /opt/ros/master/install/lib/libfastrtps.so.2.0.0: undefined reference to __atomic_store
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/test_action_typesupport_cpp_builds.dir/build.make:127: test_action_typesupport_cpp_builds] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/test_action_typesupport_cpp_builds.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
```

## System information
Ubuntu 20, Clang 11, `LDFLAGS= -fuse-ld=lld`

- Fast-RTPS version: master
- OS: Ubuntu 210
- ROS2: Master

### PR DESCRIPTION
**Pull request by rotu**
Fix #1223

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2129/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1920/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2124/)

**Comment by MiguelCompany** [comment]
The failure on Linux is not related to this PR.

**Comment by wolfv** [comment]
Is this really the correct fix?
On OS X, I am compiling with clang but don't have gcc libs available and then it seems to fail.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=170024&view=logs&jobId=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=b333111e-2fce-5fc0-5736-d5afdb3371e4

**Comment by rotu** [comment]
@wolfv I don’t know. After doing a little research it’s still unclear to me whether this library should be present in Clang 9 on Mac. It’s odd that the build setup uses bare clang instead of the Clang distributed with XCode, though I don’t know how this affects things.

**Comment by wolfv** [comment]
yeah I am convinced this fix is not portable (only works on linux).

https://github.com/STEllAR-GROUP/hpx/issues/2884

This is the advertised fix https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CheckAtomic.cmake

**Comment by MiguelCompany** [comment]
@rotu Could you create a PR with a fix similar to [this one](https://github.com/STEllAR-GROUP/hpx/pull/2889/files)?

**Comment by rotu** [comment]
I'm afraid I don't understand the underlying issue well enough to author the fix :-(

**Pull request merged**
