### PR TITLE
Release 1.8.1 [5693]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR:
* Fully implements Liveliness QoS
* Adds some regression tests
* Fixes some data races
* Fixes issues when closing participants
* Improves fastrtpsgen

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Running tests manually:

```
python3 buildcop.py --ci-repo https://gitlab.intranet.eprosima.com/eProsima/fastrtps-ci.git --source-branch  release/1.8.1 --target-branch master --build-args --mixin rel-with-deb-info --event-handlers console_cohesion+ console_package_list+ --packages-up-to fastrtps --cmake-args -DSECURITY=ON --- --test-args --packages-up-to --ctest-args --timeout 300
```

**Comment by nuclearsandwich** [comment]
I've started a full ROS 2 CI run. This does not include the changes to remove the Not Implemented Errors for liveliness QoS in rmw_fastrtps. @emersonknapp is looking into getting a PR open for that and then we'll test that as well.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7445/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3591/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6108/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7283/)

**Comment by emersonknapp** [comment]
@nuclearsandwich see https://github.com/ros2/rmw_fastrtps/pull/296

And my latest comment here https://github.com/eProsima/Fast-RTPS/issues/503#issuecomment-506019430, the `Participant::assert_liveliness` API has not been added, as far as I can see

**Comment by emersonknapp** [comment]
@MiguelCompany should we expect the `Participant::assert_liveliness` API in this release? If not, is it planned for future work? Thanks!

**Comment by MiguelCompany** [comment]
> should we expect the `Participant::assert_liveliness` API in this release?

It has been added on #579. Should be working as it just consists of calling the appropriate internal method

**Comment by raquelalvarezbanos** [comment]
Build & tests:

* All tests passed on Ubuntu (5 iterations)

**Comment by raquelalvarezbanos** [comment]
Merging, as failing test is known to fail some times.

**Pull request merged**
