### PR TITLE
Participant allocation qos [5022]

### PR DESCRIPTION
**Pull request by MiguelCompany**
Note: draft pull request as it is built on top of #462

This PR introduces new participant attributes to allow the allocation configuration for collections depending on:
* The total number of participants
* The total number of readers
* The total number of writers

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1448/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1414/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1425/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1451/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1417/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1428/)

**Comment by MiguelCompany** [comment]
Closing this in favor of #479

**Pull request closed without merging**
