### PR TITLE
Example Log migration to FastDDS [6584]

### PR DESCRIPTION
**Pull request by LuisGP**
Example code of migration guide:
https://gitlab.intranet.eprosima.com/eProsima/fastrtps/wikis/deprecation

This unneeded and small PR should be done eventually. Doing so as the migration guide example is very useful for learning purposes.

It is divided into 4 commits, in order:

* Apply coding style.
* Move and copy source and header files.
* Fix CMakeLists.txt files of broken unit tests.
* Modify header guards, include files and namespaces, adding aliases in old API.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/639/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/557/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/635/)
* Performance [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Performance%20Tests%20Localhost/116/)

**Comment by raquelalvarezbanos** [comment]
@LuisGP Windows reports 3 new warnings

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/647/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/561/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/643/)
* Performance [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Performance%20Tests%20Localhost/125/)

**Comment by raquelalvarezbanos** [comment]
@LuisGP  there is still one warning

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/658/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/571/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/654/)
* Performance [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Performance%20Tests%20Localhost/135/)

**Comment by raquelalvarezbanos** [comment]
Merging, as Windows failed due to `SimpleComunicationSecureBestEffort` and performance test failures can't be related.

**Pull request merged**
