### PR TITLE
Readers: Resource limits on the number of matched writers [4654]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR:
* Adds `matched_publisher_allocation` to `SubscriberAttributes`
* Adds `matched_writers_allocation` to `ReaderAttributes`
* Adds a dependency on [foonathan_memory](https://github.com/foonathan/memory)
* Refactors the collections on `RTPSReader`, `StatelessReader` and `StatefulReader` that depend on the number of matched writers to be resouce limited by `matched_writers_allocation`.
* Refactors `WriterProxy` to allow for its reuse and having a pool on `StatefulReader`
* Refactors the collections on `WriterProxy` that depend on the resource limits of the writer's history to be resource limited.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1299/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1269/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1282/)

**Comment by MiguelCompany** [comment]
Tests have obviously failed as we have to update the build farm with the new dependency: [foonathan_memory](https://github.com/foonathan/memory)

**Comment by MiguelCompany** [comment]
@dejanpan FYI

**Comment by dejanpan** [comment]
@MiguelCompany we won't be able to review it all . is there anything in particular you need our input on?

Ping @deeplearningrobotics with it.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1410/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1379/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1390/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1411/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1380/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1391/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1417/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1386/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1397/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1421/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1390/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1401/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1424/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1393/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1404/)

**Comment by MiguelCompany** [comment]
Closing this in favor of #479

**Pull request closed without merging**
