### PR TITLE
RTPSMessageGroup_t preallocation <1.9.x> [7165]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR:
* Adds a `SendBuffersManager` class, responsible of RTPSMessageGroup_t allocation
* Adds a `send_buffers` field to `RTPSParticipantAllocationAttributes` with the allocation options for the pool of `RTPSMessageGroup_t` instances
* Adds the corresponding XML parsing and test

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1107/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/923/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1107/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1112/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/926/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1112/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1113/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/927/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1113/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1271/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1057/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1268/)

**Comment by fmorgner** [comment]
Sorry for commenting after the merge but https://github.com/eProsima/Fast-RTPS/commit/764718dc3b3b49a7f2e3c970516c3b6724b667cd breaks compilation when security is disabled. The dtor of `RTPSMessageGroup` always accesses the member `participant_` which is only declared when `HAVE_SECURITY` is true.

dtor of `RTPSMessageGroup`:
https://github.com/eProsima/Fast-RTPS/blob/764718dc3b3b49a7f2e3c970516c3b6724b667cd/src/cpp/rtps/messages/RTPSMessageGroup.cpp#L137-L150

declaration of `participant_`
https://github.com/eProsima/Fast-RTPS/blob/83cd23d44531d6fd7db30c766d5666d20f0e1140/include/fastrtps/rtps/messages/RTPSMessageGroup.h#L225-L229

**Comment by MiguelCompany** [comment]
@fmorgner Thanks for the catch! Fixed by #979

**Pull request merged**
