### PR TITLE
Fixes for UWP

### PR DESCRIPTION
**Pull request by esteve**
These are just a few fixes for UWP. I also renamed `interface` to avoid collisions with MSVC:

https://msdn.microsoft.com/en-us/library/737cydt1.aspx

### CODE REVIEW

**Comment by esteve** [comment]
@richiprosima @JaimeMartin any feedback? Thanks.

**Comment by richiware** [comment]
Can you rebase it agains current master and I will test it today against our CI.

**Comment by esteve** [comment]
Done.

**Comment by richiware** [comment]
Thanks for the contribution

**Pull request merged**
