### PR TITLE
CMake: only if the dependencies don't exist locally, check for the thirdparty submodules

### PR DESCRIPTION
**Pull request by TSC21**
While creating some specific packages to _homebrew_ for usage in the PX4 MacOS toolchain, I found out that the Fast-RTPS is tightly dependent of the third-party submodules, which IMHO doesn't make much sense, unless you are doing versioning control on those, which at a first glance doesn't look like.

Another thing that happens is that anyone trying to build and install the binaries available in your website will run into this issue where none of the third-party submodules are initialised and the folders are empty, so it will immediately result in a build error.

So the solution I propose is to look for the dependencies first system wide, and only if they don't exist, then we use `eprosima_find_thirdparty()`. I also added the option to look for the ROS installed `tinyxml2_vendor` CMake module in case it is available (which I think it makes sense since there's a big chance you are using this in a system with ROS (2) in it).

@MiguelCompany @LuisGP @richiprosima for your review and acceptance if possible.

**Note:** If this is possible to backport to 1.9.3 and 1.9.4, it would be helpful, otherwise I will have to apply this manually on the `homebrew` packages.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1721/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1478/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1713/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1726/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1483/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1718/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1735/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1492/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1727/)

**Comment by TSC21** [comment]
@IkerLuengo @laura-eprosima FYI as well.

**Comment by TSC21** [comment]
Can someone please review this PR? It should not take longer than 5 minutes. Thank you.

**Comment by TSC21** [comment]
@richiware @MiguelCompany friendly ping

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1989/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1721/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1983/)

**Comment by TSC21** [comment]
Is this going to be reviewed or not? If not, please let me know and I will close the PR if there's no interest in bringing this in. But some feedback, even if short, is appreciated.

**Comment by TSC21** [comment]
@MiguelCompany you mean necessary or unnecessary?

**Comment by TSC21** [comment]
@MiguelCompany the only reason I added this change was because I was trying to build your release code in MacOS and since you don't export the submodules with the release, the build automatically failed, even with the dependencies like Asio or TinyXML2 installed on the system. If you say the default behaviour should use a `find_package()`, then it doesn't seem to be working correctly.

**Comment by TSC21** [comment]
I am closing this for further inspection. Thanks

**Comment by MiguelCompany** [comment]
> @MiguelCompany you mean necessary or unnecessary?

Sorry, I meant `not necessary`

**Pull request closed without merging**
